-- ========================================
-- EDA Report: Sales, Customers, and Products
-- ========================================

-- 1️⃣ Total Customers by Country
SELECT 
    country, 
    COUNT(DISTINCT customer_key) AS total_customers
FROM dbo.dim_customer
GROUP BY country;

-- 2️⃣ Total Customers by Gender
SELECT 
    gender, 
    COUNT(DISTINCT customer_key) AS total_customers
FROM dbo.dim_customer
GROUP BY gender;

-- 3️⃣ Total Products by Category
SELECT 
    category, 
    COUNT(DISTINCT product_key) AS total_products
FROM dbo.dim_products
GROUP BY category;

-- 4️⃣ Average Cost in Each Category
SELECT 
    category, 
    AVG(cost) AS avg_cost
FROM dbo.dim_products
GROUP BY category;

-- 5️⃣ Total Revenue Generated for Each Category
SELECT 
    p.category, 
    SUM(f.sales_amount) AS total_revenue
FROM dbo.fact_sales f
JOIN dbo.dim_products p ON f.product_key = p.product_key
GROUP BY p.category;

-- 6️⃣ Total Revenue Generated by Each Customer
SELECT 
    c.customer_key,
    c.country,
    SUM(f.sales_amount) AS customer_revenue
FROM dbo.fact_sales f
JOIN dbo.dim_customer c ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.country;

-- 7️⃣ Distribution of Sold Items Across Countries
SELECT 
    c.country, 
    SUM(f.quantity) AS total_items_sold
FROM dbo.fact_sales f
JOIN dbo.dim_customer c ON f.customer_key = c.customer_key
GROUP BY c.country;
